### ISSUE TITLE
Multi-line parameters support

### ISSUE THREAD

**Issue by calebeby** [AndrewRadev/dsf.vim#4]
Hi!

It would be great if this plugin could support manipulating functions that are multiple lines long, for example:

```
a(
  'b',
  'c',
  'd',
  'e',
  'f'
)
```

Currently, it looks like `dsf` doesn't recognize the function because it is multiple lines long. Is this something that is possible to change?

Thanks again!

**Comment by AndrewRadev** [comment]
You're right, currently, the plugin only works for single-line expressions. I think I originally wanted to avoid accidentally jumping to function calls that have nothing to do with the current expression, but actually, I now check that the cursor is between the found opening and closing parts, so maybe it would be okay.

I've created a branch, [multiline-support](https://github.com/AndrewRadev/dsf.vim/tree/multiline-support) where I've started implementing it. So far, it seems to work, although I should write some tests and look for issues with the existing cases. If you'd like, you could try using it for a while and let me know if you run into any issues.

For instance, deleting the surrounding function call of your example doesn't produce something great in terms of indentation, since the plugin only deletes the surroundings, and doesn't know what the contents are or how they should be adjusted. Although your particular example doesn't really produce a correct expression anyway, so maybe that's fine in most realistic cases. Let me know what you think.

**Comment by calebeby** [comment]
Thanks @AndrewRadev! It works great!

There is one thing that appears not to be working, I'm not sure whether it is related to these changes:

```
var result = function_call(CURSOR_HERE, two);
var result = function_call(one, two);
```

If I run `daf` on CURSOR_HERE, it deletes the second function call instead of the first one

**Comment by AndrewRadev** [comment]
Good catch -- it's sort of related to the multiline stuff. The `daf` mapping looks forwards for a function first, and only if it succeeds, it looks backwards. Because the search is no longer limited to a single line, the forward search succeeds first with the next function call.

This behaviour is actually necessary for *some* pieces of logic, like the "delete next surrounding function call" mapping. But I think I managed to parameterize the helper functions to fix the issue and maintain the previous functionality. Your example should work now, let me know if it does.

**Comment by calebeby** [comment]
Yep, it is working, thanks!

**Comment by AndrewRadev** [comment]
I've added auto-indentation for situations with nested function calls like this:

``` ruby
foo(
  bar(
    one,
    two
  )
)

# dsf on "one":

foo(
  one,
  two
)
```

I'm not sure if it'll work correctly for all cases, but I think it's okay if I keep it in master at this point, so I've merged the branch. It should only be triggered for very specific cases anyway.

For now, I'll close this issue, but if you run into any problems, feel free to reopen or to create a new one.
